import sqlalchemy as sa
import sqlalchemy.orm as orm
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import DateTime, Column, Integer
from sqlalchemy.sql import func
from typing import List
from log import log

# Reminder -> back_populates is necessary to avoid a bunch of warnings and subtle bugs
BaseModel = declarative_base()
BaseModel.id = Column(Integer, primary_key=True, index=True)
BaseModel.created_at = Column(DateTime, default=func.now())
BaseModel.updated_at = Column(DateTime, default=func.now(), onupdate=func.now())

def set_primary_images(model):
    model.screencap_image = None
    model.poster_image = None
    screencap_is_meta = False
    poster_is_meta = False
    if not model.image_files:
        return model
    for image_file in model.image_files:
        if not model.poster_image or poster_is_meta:
            if 'poster' in image_file.kind:
                model.poster_image = image_file
                poster_is_meta = '/metadata/' in image_file.local_path
        if not model.screencap_image or screencap_is_meta:
            if 'screencap' in image_file.kind:
                model.screencap_image = image_file
                screencap_is_meta = '/metadata/' in image_file.local_path
    return model

class User(BaseModel):
    @orm.reconstructor
    def init_on_load(self):
        self.model_kind = 'snowstream_user'
    __tablename__ = "snowstream_user"
    username = sa.Column(sa.Text, nullable=False)
    display_name = sa.Column(sa.Text, nullable=True)
    hashed_password = sa.Column(sa.Text, nullable=True)
    enabled = sa.Column(sa.Boolean)
    permissions = sa.Column(sa.Text)
    has_password = sa.Column(sa.Boolean, nullable=False)
    access_tags: orm.Mapped[List["Tag"]] = orm.relationship(secondary="user_tag")
    access_shelves: orm.Mapped[List["Shelf"]] = orm.relationship(secondary="user_shelf")
    access_crates: orm.Mapped[List["Crate"]] = orm.relationship(secondary="user_crate")

    def is_admin(self):
        return 'admin' in self.permissions

# This is a ticket for admission
# It tells snowstream
# - who the user is
# - what device the user is on
# - who counts for having watched content
# - what content the user is allowed to view
# This is only generated by the app server, and never stored in the DB
class Ticket:
    def __init__(self,ignore_watch_group:bool=False):
        self.client = None
        self.cduid = None
        self.watch_group = None
        if ignore_watch_group:
            self.watch_group = [-1]
        self.tag_ids = None
        self.shelf_ids = None
        self.crate_ids = None

    def tag_csv(self):
        return ','.join([f'{xx}' for xx in self.tag_ids])

    def has_shelf_restrictions(self):
        return self.shelf_ids != None

    def has_tag_restrictions(self):
        return self.tag_ids != None

    def has_crate_restrictions(self):
        return self.crate_ids != None

    def is_allowed(self,
        crate_id:int=None,
        tag_id:int=None,
        shelf_id:int=None,
        tag_ids:list[int]=None,
        tag_provider=None
    ):
        if crate_id != None:
            if self.crate_ids == None:
                return True
            return crate_id in self.crate_ids
        if tag_id != None:
            if self.tag_ids == None:
                return True
            return tag_id in self.tag_ids
        if shelf_id != None:
            if self.shelf_ids == None:
                return True
            return shelf_id in self.shelf_ids
        if tag_ids != None:
            if self.tag_ids == None:
                return True
            if not tag_ids:
                return False
            for allowed_tag_id in self.tag_ids:
                if allowed_tag_id in tag_ids:
                    return True
            return False
        if tag_provider != None:
            if self.tag_ids == None:
                return True
            tag_ids = tag_provider()
            if not tag_ids:
                return False
            for allowed_tag_id in self.tag_ids:
                if allowed_tag_id in tag_ids:
                    return True
            return False
        return True

class UserTag(BaseModel):
    __tablename__ = "user_tag"
    user_id: orm.Mapped[int] = orm.mapped_column(sa.ForeignKey("snowstream_user.id"))
    tag_id: orm.Mapped[int] = orm.mapped_column(sa.ForeignKey("tag.id"))

class UserShelf(BaseModel):
    __tablename__ = "user_shelf"
    user_id: orm.Mapped[int] = orm.mapped_column(sa.ForeignKey("snowstream_user.id"))
    shelf_id: orm.Mapped[int] = orm.mapped_column(sa.ForeignKey("shelf.id"))

class UserStreamSource(BaseModel):
    __tablename__ = "user_stream_source"
    user_id: orm.Mapped[int] = orm.mapped_column(sa.ForeignKey("snowstream_user.id"))
    stream_source_id: orm.Mapped[int] = orm.mapped_column(sa.ForeignKey("stream_source.id"))

class ClientDevice(BaseModel):
    __tablename__ = "client_device"
    reported_name = sa.Column(sa.Text)
    display_name = sa.Column(sa.Text)
    device_kind = sa.Column(sa.Text)

class ClientDeviceUser(BaseModel):
    __tablename__ = "client_device_user"
    user_id: orm.Mapped[int] = orm.mapped_column(sa.ForeignKey("snowstream_user.id"),nullable=False)
    client_device_id: orm.Mapped[int] = orm.mapped_column(sa.ForeignKey("client_device.id"),nullable=False)
    client_device: orm.Mapped['ClientDevice'] = orm.relationship()
    isolation_mode = sa.Column(sa.Text)
    last_connection = sa.Column(sa.DateTime)

class CachedText(BaseModel):
    __tablename__ = "cached_text"
    key = sa.Column(sa.Text)
    data = sa.Column(sa.Text)
    time_to_live_seconds = sa.Column(sa.Integer)

class Job(BaseModel):
    __tablename__ = "job"
    kind = sa.Column(sa.Text)
    message = sa.Column(sa.Text)
    status = sa.Column(sa.Text)
    logs_json = sa.Column(sa.Text)
    input_json = sa.Column(sa.Text)

class Tag(BaseModel):
    __tablename__ = "tag"
    name = sa.Column(sa.Text)
    movies: orm.Mapped[List["Movie"]] = orm.relationship(secondary="movie_tag",back_populates="tags")
    shows: orm.Mapped[List["Show"]] = orm.relationship(secondary="show_tag",back_populates="tags")
    show_seasons: orm.Mapped[List["ShowSeason"]] = orm.relationship(secondary="show_season_tag",back_populates="tags")
    show_episodes: orm.Mapped[List["ShowEpisode"]] = orm.relationship(secondary="show_episode_tag",back_populates="tags")
    stream_sources: orm.Mapped[List["StreamSource"]] = orm.relationship(secondary="stream_source_tag",back_populates="tags")
    streamables: orm.Mapped[List["Streamable"]] = orm.relationship(secondary="streamable_tag",back_populates="tags")
    rules: orm.Mapped[List["TagRule"]] = orm.relationship(back_populates="tag")

class ImageFile(BaseModel):
    @orm.reconstructor
    def init_on_load(self):
        self.model_kind = 'image_file'
    __tablename__ = "image_file"
    shelf_id: orm.Mapped[int] = orm.mapped_column(sa.ForeignKey("shelf.id"))
    kind = sa.Column(sa.Text)
    local_path = sa.Column(sa.Text)
    web_path = sa.Column(sa.Text)
    network_path = sa.Column(sa.Text)
    thumbnail_web_path = sa.Column(sa.Text)
    movie: orm.Mapped["Movie"] = orm.relationship(secondary="movie_image_file", back_populates="image_files")
    movie_image_file: orm.Mapped["MovieImageFile"] = orm.relationship(back_populates="image_file",overlaps="movie")
    show_episode: orm.Mapped["ShowEpisode"] = orm.relationship(secondary="show_episode_image_file", back_populates="image_files")
    show_episode_image_file: orm.Mapped["ShowEpisodeImageFile"] = orm.relationship(back_populates="image_file",overlaps="show_episode")
    show_season: orm.Mapped["ShowSeason"] = orm.relationship(secondary="show_season_image_file", back_populates="image_files")
    show_season_image_file: orm.Mapped["ShowSeasonImageFile"] = orm.relationship(back_populates="image_file",overlaps="show_season")
    show: orm.Mapped["Show"] = orm.relationship(secondary="show_image_file", back_populates="image_files")
    show_image_file: orm.Mapped["ShowImageFile"] = orm.relationship(back_populates="image_file",overlaps="show")
    crate: orm.Mapped["Crate"] = orm.relationship(secondary="crate_image_file", back_populates="image_files")
    crate_image_file: orm.Mapped["CrateImageFile"] = orm.relationship(back_populates="image_file",overlaps="crate")

class MetadataFile(BaseModel):
    @orm.reconstructor
    def init_on_load(self):
        self.model_kind = 'metadata_file'
    __tablename__ = "metadata_file"
    shelf_id: orm.Mapped[int] = orm.mapped_column(sa.ForeignKey("shelf.id"))
    kind = sa.Column(sa.Text)
    local_path = sa.Column(sa.Text)
    web_path = sa.Column(sa.Text)
    network_path = sa.Column(sa.Text)
    xml_content = sa.Column(sa.Text)
    movie: orm.Mapped["Movie"] = orm.relationship(secondary="movie_metadata_file", back_populates="metadata_files")
    movie_metadata_file: orm.Mapped["MovieMetadataFile"] = orm.relationship(back_populates="metadata_file",overlaps="movie")
    show_episode: orm.Mapped["ShowEpisode"] = orm.relationship(secondary="show_episode_metadata_file", back_populates="metadata_files")
    show_episode_metadata_file: orm.Mapped["ShowEpisodeMetadataFile"] = orm.relationship(back_populates="metadata_file",overlaps="show_episode")
    show_season: orm.Mapped["ShowSeason"] = orm.relationship(secondary="show_season_metadata_file", back_populates="metadata_files")
    show_season_metadata_file: orm.Mapped["ShowSeasonMetadataFile"] = orm.relationship(back_populates="metadata_file",overlaps="show_season")
    show: orm.Mapped["Show"] = orm.relationship(secondary="show_metadata_file", back_populates="metadata_files")
    show_metadata_file: orm.Mapped["ShowMetadataFile"] = orm.relationship(back_populates="metadata_file",overlaps="show")


class AudioFile(BaseModel):
    @orm.reconstructor
    def init_on_load(self):
        self.model_kind = 'audio_file'
    __tablename__ = "audio_file"
    shelf_id: orm.Mapped[int] = orm.mapped_column(sa.ForeignKey("shelf.id"))
    kind = sa.Column(sa.Text)
    local_path = sa.Column(sa.Text)
    web_path = sa.Column(sa.Text)
    network_path = sa.Column(sa.Text)
    snowstream_info_json = sa.Column(sa.Text)
    ffprobe_raw_json = sa.Column(sa.Text)
    mediainfo_raw_json = sa.Column(sa.Text)
    version = sa.Column(sa.Text)
    name = sa.Column(sa.Text)
    movie: orm.Mapped["Movie"] = orm.relationship(secondary="movie_audio_file", back_populates="audio_files")
    movie_audio_file: orm.Mapped["MovieAudioFile"] = orm.relationship(back_populates="audio_file",overlaps="movie")
    show_episode: orm.Mapped["ShowEpisode"] = orm.relationship(secondary="show_episode_audio_file", back_populates="audio_files")
    show_episode_audio_file: orm.Mapped["ShowEpisodeAudioFile"] = orm.relationship(back_populates="audio_file",overlaps="show_episode")
    crate: orm.Mapped["Crate"] = orm.relationship(secondary="crate_audio_file", back_populates="audio_files")
    crate_audio_file: orm.Mapped["CrateAudioFile"] = orm.relationship(back_populates="audio_file",overlaps="crate")
    thumbnail_web_path = sa.Column(sa.Text)

class Shelf(BaseModel):
    @orm.reconstructor
    def init_on_load(self):
        self.model_kind = 'shelf'
    __tablename__ = "shelf"
    name = sa.Column(sa.Text)
    kind = sa.Column(sa.Text)
    local_path = sa.Column(sa.Text)
    network_path = sa.Column(sa.Text)
    movies: orm.Mapped[List["Movie"]] = orm.relationship(secondary="movie_shelf",back_populates="shelf")
    shows: orm.Mapped[List["Show"]] = orm.relationship(secondary="show_shelf",back_populates="shelf")
    crates: orm.Mapped[List["Crate"]] = orm.relationship(secondary="crate_shelf",back_populates="shelf")


class Movie(BaseModel):
    @orm.reconstructor
    def init_on_load(self):
        self.model_kind = 'movie'
    __tablename__ = "movie"
    name = sa.Column(sa.Text)
    release_year = sa.Column(sa.Integer)
    directory = sa.Column(sa.Text)
    remote_metadata_id = sa.Column(sa.Integer)
    remote_metadata_source = sa.Column(sa.Text)
    in_progress: orm.Mapped["WatchProgress"] = orm.relationship(overlaps="movie", back_populates="movie")
    tags: orm.Mapped[List["Tag"]] = orm.relationship(secondary="movie_tag",back_populates="movies")
    audio_files: orm.Mapped[List["AudioFile"]] = orm.relationship(secondary="movie_audio_file",back_populates="movie",overlaps="movie_audio_file")
    image_files: orm.Mapped[List["ImageFile"]] = orm.relationship(secondary="movie_image_file",back_populates="movie",overlaps="movie_image_file")
    metadata_files: orm.Mapped[List["MetadataFile"]] = orm.relationship(secondary="movie_metadata_file",back_populates="movie",overlaps="movie_metadata_file")
    shelf: orm.Mapped["Shelf"] = orm.relationship(secondary="movie_shelf")
    watch_count: orm.Mapped['WatchCount'] = orm.relationship(overlaps="movie")

    def get_tag_ids(self):
        if not self.tags:
            return []
        return [xx.id for xx in self.tags]

class MovieShelf(BaseModel):
    __tablename__ = "movie_shelf"
    movie_id = sa.Column(sa.Integer, sa.ForeignKey("movie.id"))
    shelf_id = sa.Column(sa.Integer, sa.ForeignKey("shelf.id"))


class MovieTag(BaseModel):
    __tablename__ = "movie_tag"
    movie_id = sa.Column(sa.Integer, sa.ForeignKey("movie.id"))
    tag_id = sa.Column(sa.Integer, sa.ForeignKey("tag.id"))


class MovieImageFile(BaseModel):
    __tablename__ = "movie_image_file"
    movie_id = sa.Column(sa.Integer, sa.ForeignKey("movie.id"))
    image_file_id = sa.Column(sa.Integer, sa.ForeignKey("image_file.id"))
    image_file: orm.Mapped['ImageFile'] = orm.relationship(back_populates='movie_image_file',overlaps="movie,image_files")


class MovieMetadataFile(BaseModel):
    __tablename__ = "movie_metadata_file"
    movie_id = sa.Column(sa.Integer, sa.ForeignKey("movie.id"))
    metadata_file_id = sa.Column(sa.Integer, sa.ForeignKey("metadata_file.id"))
    metadata_file: orm.Mapped['MetadataFile'] = orm.relationship(back_populates='movie_metadata_file',overlaps="movie,metadata_files")


class MovieAudioFile(BaseModel):
    __tablename__ = "movie_audio_file"
    movie_id = sa.Column(sa.Integer, sa.ForeignKey("movie.id"))
    audio_file_id = sa.Column(sa.Integer, sa.ForeignKey("audio_file.id"))
    audio_file: orm.Mapped['AudioFile'] = orm.relationship(back_populates="movie_audio_file",overlaps="movie,audio_files")

class Crate(BaseModel):
    @orm.reconstructor
    def init_on_load(self):
        self.model_kind = 'crate'
    __tablename__ = "crate"
    directory = sa.Column(sa.Text)
    audio_files: orm.Mapped[List["AudioFile"]] = orm.relationship(secondary="crate_audio_file",back_populates="crate",overlaps="crate_audio_file")
    image_files: orm.Mapped[List["ImageFile"]] = orm.relationship(secondary="crate_image_file",back_populates="crate",overlaps="crate_image_file")
    shelf: orm.Mapped["Shelf"] = orm.relationship(secondary="crate_shelf")

class CrateShelf(BaseModel):
    __tablename__ = "crate_shelf"
    crate_id = sa.Column(sa.Integer, sa.ForeignKey("crate.id"))
    shelf_id = sa.Column(sa.Integer, sa.ForeignKey("shelf.id"))

class CrateAudioFile(BaseModel):
    __tablename__ = "crate_audio_file"
    crate_id = sa.Column(sa.Integer, sa.ForeignKey("crate.id"))
    audio_file_id = sa.Column(sa.Integer, sa.ForeignKey("audio_file.id"))
    audio_file: orm.Mapped['AudioFile'] = orm.relationship(back_populates="crate_audio_file",overlaps="crate,audio_files")

class CrateImageFile(BaseModel):
    __tablename__ = "crate_image_file"
    crate_id = sa.Column(sa.Integer, sa.ForeignKey("crate.id"))
    image_file_id = sa.Column(sa.Integer, sa.ForeignKey("image_file.id"))
    image_file: orm.Mapped['ImageFile'] = orm.relationship(back_populates='crate_image_file',overlaps="crate,image_files")

class DisplayCleanupRule(BaseModel):
    __tablename__ = 'display_cleanup_rule'
    target_kind = sa.Column(sa.Text)
    rule_kind = sa.Column(sa.Text)
    priority = sa.Column(sa.Integer)
    needle = sa.Column(sa.Text)
    replacement = sa.Column(sa.Text)

class TagRule(BaseModel):
    __tablename__ = 'tag_rule'
    tag_id: orm.Mapped[int] = orm.mapped_column(sa.ForeignKey("tag.id"))
    tag: orm.Mapped["Tag"] = orm.relationship(back_populates="rules")
    rule_kind = sa.Column(sa.Text)
    target_kind = sa.Column(sa.Text)
    priority = sa.Column(sa.Integer)
    trigger_kind = sa.Column(sa.Text)
    trigger_target = sa.Column(sa.Text)