import sqlalchemy as sa
import sqlalchemy.orm as orm
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import DateTime, Column, Integer
from sqlalchemy.sql import func
from typing import List
from log import log

# Reminder -> back_populates is necessary to avoid a bunch of warnings and subtle bugs
BaseModel = declarative_base()
BaseModel.id = Column(Integer, primary_key=True, index=True)
BaseModel.created_at = Column(DateTime, default=func.now())
BaseModel.updated_at = Column(DateTime, default=func.now(), onupdate=func.now())

def set_primary_images(model):
    model.screencap_image = None
    model.poster_image = None
    screencap_is_meta = False
    poster_is_meta = False
    if not model.image_files:
        return model
    for image_file in model.image_files:
        if not model.poster_image or poster_is_meta:
            if 'poster' in image_file.kind:
                model.poster_image = image_file
                poster_is_meta = '/metadata/' in image_file.local_path
        if not model.screencap_image or screencap_is_meta:
            if 'screencap' in image_file.kind:
                model.screencap_image = image_file
                screencap_is_meta = '/metadata/' in image_file.local_path
    return model

class User(BaseModel):
    @orm.reconstructor
    def init_on_load(self):
        self.model_kind = 'snowgroove_user'
    __tablename__ = "snowgroove_user"
    username = sa.Column(sa.Text, nullable=False)
    display_name = sa.Column(sa.Text, nullable=True)
    hashed_password = sa.Column(sa.Text, nullable=True)
    enabled = sa.Column(sa.Boolean)
    permissions = sa.Column(sa.Text)
    has_password = sa.Column(sa.Boolean, nullable=False)
    access_tags: orm.Mapped[List["Tag"]] = orm.relationship(secondary="snowgroove_user_tag")
    access_shelves: orm.Mapped[List["Shelf"]] = orm.relationship(secondary="snowgroove_user_shelf")
    access_crates: orm.Mapped[List["Crate"]] = orm.relationship(secondary="snowgroove_user_crate")

    def is_admin(self):
        return 'admin' in self.permissions

# This is a ticket for admission
# It tells snowgroove
# - who the user is
# - what device the user is on
# - who counts for having watched content
# - what content the user is allowed to view
# This is only generated by the app server, and never stored in the DB
class Ticket:
    def __init__(self,ignore_watch_group:bool=False):
        self.client = None
        self.cduid = None
        self.watch_group = None
        if ignore_watch_group:
            self.watch_group = [-1]
        self.tag_ids = None
        self.shelf_ids = None
        self.crate_ids = None

    def tag_csv(self):
        return ','.join([f'{xx}' for xx in self.tag_ids])

    def has_shelf_restrictions(self):
        return self.shelf_ids != None

    def has_tag_restrictions(self):
        return self.tag_ids != None

    def has_crate_restrictions(self):
        return self.crate_ids != None

    def is_allowed(self,
        crate_id:int=None,
        tag_id:int=None,
        shelf_id:int=None,
        tag_ids:list[int]=None,
        tag_provider=None
    ):
        if crate_id != None:
            if self.crate_ids == None:
                return True
            return crate_id in self.crate_ids
        if tag_id != None:
            if self.tag_ids == None:
                return True
            return tag_id in self.tag_ids
        if shelf_id != None:
            if self.shelf_ids == None:
                return True
            return shelf_id in self.shelf_ids
        if tag_ids != None:
            if self.tag_ids == None:
                return True
            if not tag_ids:
                return False
            for allowed_tag_id in self.tag_ids:
                if allowed_tag_id in tag_ids:
                    return True
            return False
        if tag_provider != None:
            if self.tag_ids == None:
                return True
            tag_ids = tag_provider()
            if not tag_ids:
                return False
            for allowed_tag_id in self.tag_ids:
                if allowed_tag_id in tag_ids:
                    return True
            return False
        return True

class UserTag(BaseModel):
    __tablename__ = "snowgroove_user_tag"
    snowgroove_user_id: orm.Mapped[int] = orm.mapped_column(sa.ForeignKey("snowgroove_user.id"))
    tag_id: orm.Mapped[int] = orm.mapped_column(sa.ForeignKey("tag.id"))

class UserShelf(BaseModel):
    __tablename__ = "snowgroove_user_shelf"
    snowgroove_user_id: orm.Mapped[int] = orm.mapped_column(sa.ForeignKey("snowgroove_user.id"))
    shelf_id: orm.Mapped[int] = orm.mapped_column(sa.ForeignKey("shelf.id"))

class UserCrate(BaseModel):
    __tablename__ = "snowgroove_user_crate"
    snowgroove_user_id: orm.Mapped[int] = orm.mapped_column(sa.ForeignKey("snowgroove_user.id"))
    crate_id: orm.Mapped[int] = orm.mapped_column(sa.ForeignKey("crate.id"))

class ClientDevice(BaseModel):
    __tablename__ = "client_device"
    reported_name = sa.Column(sa.Text)
    display_name = sa.Column(sa.Text)
    device_kind = sa.Column(sa.Text)

class ClientDeviceUser(BaseModel):
    __tablename__ = "client_device_user"
    snowgroove_user_id: orm.Mapped[int] = orm.mapped_column(sa.ForeignKey("snowgroove_user.id"),nullable=False)
    client_device_id: orm.Mapped[int] = orm.mapped_column(sa.ForeignKey("client_device.id"),nullable=False)
    client_device: orm.Mapped['ClientDevice'] = orm.relationship()
    isolation_mode = sa.Column(sa.Text)
    last_connection = sa.Column(sa.DateTime)

class CachedText(BaseModel):
    __tablename__ = "cached_text"
    key = sa.Column(sa.Text)
    data = sa.Column(sa.Text)
    time_to_live_seconds = sa.Column(sa.Integer)

class Job(BaseModel):
    __tablename__ = "job"
    kind = sa.Column(sa.Text)
    message = sa.Column(sa.Text)
    status = sa.Column(sa.Text)
    logs_json = sa.Column(sa.Text)
    input_json = sa.Column(sa.Text)

class Tag(BaseModel):
    __tablename__ = "tag"
    name = sa.Column(sa.Text)
    albums: orm.Mapped[List["Album"]] = orm.relationship(secondary="album_tag",back_populates="tags")
    artists: orm.Mapped[List["Artist"]] = orm.relationship(secondary="artist_tag",back_populates="tags")
    crates: orm.Mapped[List["Crate"]] = orm.relationship(secondary="crate_tag",back_populates="tags")
    rules: orm.Mapped[List["TagRule"]] = orm.relationship(back_populates="tag")

class ImageFile(BaseModel):
    @orm.reconstructor
    def init_on_load(self):
        self.model_kind = 'image_file'
    __tablename__ = "image_file"
    crate_id: orm.Mapped[int] = orm.mapped_column(sa.ForeignKey("crate.id"),nullable=True)
    crate: orm.Mapped["Crate"] = orm.relationship(back_populates="image_files")
    kind = sa.Column(sa.Text)
    local_path = sa.Column(sa.Text)
    web_path = sa.Column(sa.Text)
    network_path = sa.Column(sa.Text)
    thumbnail_web_path = sa.Column(sa.Text)

class MetadataFile(BaseModel):
    @orm.reconstructor
    def init_on_load(self):
        self.model_kind = 'metadata_file'
    __tablename__ = "metadata_file"
    crate_id: orm.Mapped[int] = orm.mapped_column(sa.ForeignKey("crate.id"))
    kind = sa.Column(sa.Text)
    local_path = sa.Column(sa.Text)
    web_path = sa.Column(sa.Text)
    network_path = sa.Column(sa.Text)
    file_content = sa.Column(sa.Text)

class AudioFile(BaseModel):
    @orm.reconstructor
    def init_on_load(self):
        self.model_kind = 'audio_file'
    __tablename__ = "audio_file"
    crate_id: orm.Mapped[int] = orm.mapped_column(sa.ForeignKey("crate.id"))
    crate: orm.Mapped["Crate"] = orm.relationship()
    album = sa.Column(sa.Text)
    artist = sa.Column(sa.Text)
    disc = sa.Column(sa.Text)
    duration = sa.Column(sa.Float)
    ffprobe_raw_json = sa.Column(sa.Text)
    kind = sa.Column(sa.Text)
    local_path = sa.Column(sa.Text)
    lyrics = sa.Column(sa.Text)
    mediainfo_raw_json = sa.Column(sa.Text)
    network_path = sa.Column(sa.Text)
    path = sa.Column(sa.Text)
    position = sa.Column(sa.Text)
    snowgroove_info_json = sa.Column(sa.Text)
    thumbnail_web_path = sa.Column(sa.Text)
    fingerprint = sa.Column(sa.Text)
    title = sa.Column(sa.Text)
    track = sa.Column(sa.Text)
    web_path = sa.Column(sa.Text)
    year = sa.Column(sa.Float)

class Shelf(BaseModel):
    @orm.reconstructor
    def init_on_load(self):
        self.model_kind = 'shelf'
    __tablename__ = "shelf"
    name = sa.Column(sa.Text)
    kind = sa.Column(sa.Text)
    local_path = sa.Column(sa.Text)
    network_path = sa.Column(sa.Text)
    crates: orm.Mapped[List["Crate"]] = orm.relationship(back_populates="shelf")

class Crate(BaseModel):
    @orm.reconstructor
    def init_on_load(self):
        self.model_kind = 'crate'
    __tablename__ = "crate"
    directory = sa.Column(sa.Text)
    albums: orm.Mapped[List["Album"]] = orm.relationship(back_populates="crate")
    artists: orm.Mapped[List["Artist"]] = orm.relationship(secondary="crate_artist",back_populates="crates")
    audio_files: orm.Mapped[List["AudioFile"]] = orm.relationship(back_populates="crate")
    image_files: orm.Mapped[List["ImageFile"]] = orm.relationship(back_populates="crate")
    shelf_id: orm.Mapped[int] = orm.mapped_column(sa.ForeignKey("shelf.id"))
    shelf: orm.Mapped["Shelf"] = orm.relationship(back_populates="crates")
    tags: orm.Mapped[List["Tag"]] = orm.relationship(secondary="crate_tag",back_populates="crates")

class Artist(BaseModel):
    @orm.reconstructor
    def init_on_load(self):
        self.model_kind = 'artist'
    __tablename__ = 'artist'
    name = sa.Column(sa.Text)
    crates: orm.Mapped[List["Crate"]] = orm.relationship(secondary="crate_artist",back_populates="artists")
    tags: orm.Mapped[List["Tag"]] = orm.relationship(secondary="artist_tag",back_populates="artists")

class Album(BaseModel):
    @orm.reconstructor
    def init_on_load(self):
        self.model_kind = 'album'
    __tablename__ = 'album'
    crate_id: orm.Mapped[int] = orm.mapped_column(sa.ForeignKey("crate.id"))
    crate: orm.Mapped["Crate"] = orm.relationship(back_populates="albums")
    name = sa.Column(sa.Text)
    year = sa.Column(sa.Text)
    tags: orm.Mapped[List["Tag"]] = orm.relationship(secondary="album_tag",back_populates="albums")

class AlbumTag(BaseModel):
    __tablename__ = "album_tag"
    album_id = sa.Column(sa.Integer, sa.ForeignKey("album.id"))
    tag_id = sa.Column(sa.Integer, sa.ForeignKey("tag.id"))

class ArtistTag(BaseModel):
    __tablename__ = "artist_tag"
    artist_id = sa.Column(sa.Integer, sa.ForeignKey("artist.id"))
    tag_id = sa.Column(sa.Integer, sa.ForeignKey("tag.id"))

class CrateTag(BaseModel):
    __tablename__ = "crate_tag"
    crate_id = sa.Column(sa.Integer, sa.ForeignKey("crate.id"))
    tag_id = sa.Column(sa.Integer, sa.ForeignKey("tag.id"))

class CrateArtist(BaseModel):
    __tablename__ = "crate_artist"
    crate_id = sa.Column(sa.Integer, sa.ForeignKey("crate.id"))
    artist_id = sa.Column(sa.Integer, sa.ForeignKey("artist.id"))

class DisplayCleanupRule(BaseModel):
    __tablename__ = 'display_cleanup_rule'
    target_kind = sa.Column(sa.Text)
    rule_kind = sa.Column(sa.Text)
    priority = sa.Column(sa.Integer)
    needle = sa.Column(sa.Text)
    replacement = sa.Column(sa.Text)

class TagRule(BaseModel):
    __tablename__ = 'tag_rule'
    tag_id: orm.Mapped[int] = orm.mapped_column(sa.ForeignKey("tag.id"))
    tag: orm.Mapped["Tag"] = orm.relationship(back_populates="rules")
    rule_kind = sa.Column(sa.Text)
    target_kind = sa.Column(sa.Text)
    priority = sa.Column(sa.Integer)
    trigger_kind = sa.Column(sa.Text)
    trigger_target = sa.Column(sa.Text)